/* ######################################################################### */
/*
 * $Log: fmcGroffMacro.h,v $
 * Revision 1.3  2012/11/29 15:52:27  galli
 * Compatibility with gcc/g++ 4.4.6
 *
 * Revision 1.2  2008/10/09 08:15:36  galli
 * minor changes
 *
 * Revision 1.1  2008/09/10 06:51:16  galli
 * Initial revision
 */
/* ######################################################################### */
#ifndef _FMC_GROFF_MACRO_H
#define _FMC_GROFF_MACRO_H 1
/*****************************************************************************/
const char *groffMacro=
".\n"
".\\\" --------------------------------------------------------------------\n"
".\\\" Setup\n"
".\\\" --------------------------------------------------------------------\n"
".\n"
".mso www.tmac\n"
".\n"
".\\\" set adjust to both\n"
".ad b\n"
".\n"
".\\\" fonts of fixed length\n"
".\n"
".if n \\{\\\n"
".  mso tty-char.tmac\n"
".  ftr CR R\n"
".  ftr CI I\n"
".  ftr CB B\n"
".\\}\n"
".\n"
".if '\\*[.T]'dvi' \\\n"
".  ftr CB CW\n"
".\n"
".\\\" --------------------------------------------------------------------\n"
".\" String definitions\n"
".\n"
".ds @- \"\\-\\\"\n"
".ds @-- \"\\-\\^\\-\\\"\n"
".\n"
".ds Ellipsis .\\|.\\|.\\\"\n"
".\n"
".\n"
".\\\" --------------------------------------------------------------------\n"
".\\\" Begin of macro definitions\n"
".de c\n"
".\\\" this is like a comment request when escape mechanism is off\n"
"..\n"
".eo\n"
".\n"
".c --------------------------------------------------------------------\n"
".de TP+\n"
".br\n"
".ns\n"
".TP \\$1\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c Like TP, but if specified indent is more than half\n"
".c the current line-length - indent, use the default indent.\n"
".de Tp\n"
".  ie \\n[.$]=0:((0\\$1)*2u>(\\n.lu-\\n(.iu)) .TP\n"
".  el .TP \"\\$1\"\n"
"..\n"
".c --------------------------------------------------------------------\n"
".de Text\n"
".  nop \\)\\$*\n"
"..\n"
".c --------------------------------------------------------------------\n"
".de Synopsis\n"
".  ds @arg1 \\$1\\\"\n"
".  nr @old_indent \\n[.i]\n"
".  ad l\n"
".  in +\\w'\\f[B]\\*[@arg1]\\0'u\n"
".  ti \\n[@old_indent]u\n"
".  B \\*[@arg1]\\0\\c\n"
".  rr @old_indent\n"
".  rm @arg1\n"
"..\n"
".c --------------------------------------------------------------------\n"
".de EndSynopsis\n"
".  ad\n"
".  in\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c ShortOpt[]  (name [arg])\n"
".c\n"
".c short option in synopsis\n"
".c\n"
".de ShortOpt[]\n"
".  if \\n[.$]=0 \\\n"
".    return\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  ie \\n[.$]=0 \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\f[]\\f[R]]\\f[]\n"
".  el \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\~\\f[]\\f[I]\\/\\$*\\f[]\\f[R]]\\f[]\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c LongOpt[]  (name [arg])\n"
".c\n"
".c short option in synopsis\n"
".c\n"
".de LongOpt[]\n"
".  if \\n[.$]=0 \\\n"
".    return\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  ie \\n[.$]=0 \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@--]\\*[@opt]\\f[]\\f[R]]\\f[]\n"
".  el \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@--]\\*[@opt]\\~\\f[]\\f[I]\\/\\$*\\f[]\\f[R]]\\f[]\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c DoubleOpt[]  (names namel [arg])\n"
".c\n"
".c long option in synopsis\n"
".c\n"
".de DoubleOpt[]\n"
".  if \\n[.$]=0 \\\n"
".    return\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  ds @optl \\$1\\\"\n"
".  shift\n"
".  ie \\n[.$]=0 \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\f[R]\\~|\\~\\f[]\\*[@--]\\*[@optl]\\f[]\\f[R]]\\f[]\n"
".  el \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\f[R]\\~|\\~\\f[]\\*[@--]\\*[@optl]\\~\\f[]\\f[I]\\/\\$*\\f[]\\f[R]]\\f[]\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c Option in synopsis (short option)\n"
".de SynOpt\n"
".  if \\n[.$]=0 \\\n"
".    return\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  ie \\n[.$]=0 \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\f[]\\f[R]]\\f[]\n"
".  el \\\n"
".    Text \\f[R][\\f[]\\f[CB]\\*[@-]\\*[@opt]\\~\\f[]\\f[I]\\/\\$*\\f[]\\f[R]]\\f[]\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c ShortOpt ([char [punct]])\n"
".c\n"
".c `-c' somewhere in the text \n"
".c second arg is punctuation\n"
".c\n"
".de ShortOpt\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  Text \\f[CB]\\*[@-]\\*[@opt]\\f[]\\/\\$*\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c LongOpt  ([name [punct]])\n"
".c\n"
".c `--name' somewhere in the text \n"
".c second arg is punctuation\n"
".c\n"
".de LongOpt\n"
".  ds @opt \\$1\\\"\n"
".  shift\n"
".  Text \\f[CB]\\*[@--]\\f[]\\f[B]\\*[@opt]\\f[]\\/\\$*\n"
".  rm @opt\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c OptDef  (shortopt [longopt [argument]])\n"
".c\n"
".c option documentation\n"
".c args : `shortopt', `longopt' can be ""\n"
".c\n"
".de OptDef\n"
".  ds @short\n"
".  ds @long\n"
".  ds @arg\n"
".  if \\n[.$]>=1 \\{\\\n"
".    ds @arg1 \"\\$1\\\"\n"
".    if !'\\*[@arg1]'' \\\n"
".      ds @short \"\\f[CB]\\*[@-]\\*[@arg1]\\f[]\\\"\n"
".    if \\n[.$]>=2 \\{\\\n"
".      if !'\\*[@short]'' \\\n"
".        as @short \\f[CW]\\0\\f[]\n"
".      ds @arg2 \"\\$2\\\"\n"
".      if !'\\*[@arg2]'' \\\n"
".        ds @long \"\\f[CB]\\*[@--]\\f[]\\f[B]\\*[@arg2]\\f[]\\\"\n"
".      if \\n[.$]>=3 \\{\\\n"
".        if !'\\*[@long]'' \\\n"
".          as @long \\|\\~\\|\\\"\n"
".        shift 2\n"
".        ds @arg \\f[I]\\$*\\\"\n"
".      \\}\n"
".    \\}\n"
".  \\}\n"
".  IP \"\\f[R]\\*[@short]\\*[@long]\\*[@arg]\\f[]\"\n"
".  rm @arg\n"
".  rm @arg1\n"
".  rm @arg2\n"
".  rm @short\n"
".  rm @long\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c Continuation of an OptDef header.\n"
".de OptDef+\n"
".  br\n"
".  ns\n"
".  OptDef \\$@\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c Environment variable\n"
".de EnvVar\n"
".  SM\n"
".  BR \\$1 \\$2\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c a shell command line\n"
".de ShellCommand\n"
".  nr @font \\n[.f]\n"
".  c replace argument separator by unbreakable space\n"
".  ds @args \\$1\\\"\"\n"
".  shift\n"
".  while (\\n[.$]>0) \\{\\\n"
".    ds @args \\*[@args]\\~\\$1\n"
".    shift\n"
".  \\}\n"
".  br\n"
".  ad l\n"
".  nh\n"
".  Text \\f[I]bash$\\h'1m'\\f[P]\\f[B]\\*[@args]\\f[P]\\&\\\"\n"
".  ft R\n"
".  ft P\n"
".  hy\n"
".  ad\n"
".  ft \\n[@font]\n"
".  br\n"
".  rr @font\n"
".  rm @args\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c `char or string'\n"
".de Quoted\n"
".  ft CR\n"
".  Text \\[oq]\\$*\\[cq]\n"
".  ft\n"
"..\n"
".c --------------------------------------------------------------------\n"
".c End of macro definitions\n"
".ec\n"
".\n"
;
/*****************************************************************************/
#endif                                                 /* _FMC_GROFF_MACRO_H */
/* ######################################################################### */
